const hashA = 'a'.repeat(64)
const hashB = 'b'.repeat(64)

export const schemaFixtures = {
  'benchmark-config': {
    $schema: '../schemas/benchmark-config.schema.json',
    schemaVersion: 1,
    experimentId: 'synthetic-experiment',
    seed: 'synthetic-seed',
    sample: {
      strata: ['one', 'two', 'three', 'four'],
      calibrationPerStratum: 2,
      evaluationPerStratum: 4,
      annotatedPagesPerDocument: 2,
    },
    inspection: {
      minimumTextCharsPerPage: 32,
      fullPageImageAreaRatio: 0.8,
      mixedScriptMinimumRatio: 0.1,
    },
    routing: {
      defaults: {
        minimumTextLayerCoverage: 0.5,
        maximumFullPageImageRatio: 0.5,
        maximumEncodingAnomalyRatio: 0.02,
      },
      thresholdGrid: {
        minimumTextLayerCoverage: [0.5],
        maximumFullPageImageRatio: [0.5],
        maximumEncodingAnomalyRatio: [0.02],
      },
      tuning: { recordAllCandidates: true, tieBreak: 'conservative' },
      maxEscalations: 2,
    },
    metrics: {
      textNormalisation: {
        contractVersion: 'text-comparison-v2',
        markup: 'strip-html-tags-and-unwrap-paired-math-delimiters',
        unicodeForm: 'NFC',
        cerWhitespace: 'strip-all-unicode-whitespace',
        cerPunctuation: 'preserve',
        thaiWerWhitespace: 'strip-all-before-segmentation',
        englishWerWhitespace: 'collapse-and-trim',
        mixedWerWhitespace: 'collapse-and-trim',
        thaiWerSegmenter: 'Intl.Segmenter:th:word:isWordLike',
        englishWerSegmenter: 'Intl.Segmenter:en:word:isWordLike',
        mixedWerSegmenter: 'Intl.Segmenter:th:word:isWordLike',
        werPunctuation: 'exclude-non-word-like-segments',
        case: 'preserve',
      },
    },
    execution: { concurrency: 1, timeoutMs: 60_000 },
    cost: {
      currency: 'USD',
      cpuMachineHour: 0.1,
      gpuMachineHour: 1,
      basis: 'Synthetic declared proxy tariffs.',
    },
  },
  corpus: {
    schemaVersion: 1,
    caseId: 'F001',
    contentHash: hashA,
    mediaType: 'application/pdf',
    sizeBytes: 128,
    status: 'included',
    attachmentOrdinal: 0,
  },
  inspection: {
    schemaVersion: 1,
    caseId: 'F001',
    contentHash: hashA,
    pageCount: 1,
    pages: [
      {
        page: 1,
        textChars: 64,
        imageAreaRatio: 0.1,
        encodingAnomalyCount: 0,
        thaiChars: 0,
        latinChars: 60,
        warnings: [],
      },
    ],
    signals: {
      totalTextChars: 64,
      charsPerPage: 64,
      textLayerCoverage: 1,
      charsPerPageCv: 0,
      meanImageAreaRatio: 0.1,
      fullPageImageRatio: 0,
      encodingAnomalyRatio: 0,
      thaiCharRatio: 0,
      latinCharRatio: 1,
      mixedScript: false,
    },
    metadata: { producer: 'synthetic' },
    warnings: [],
  },
  sample: {
    schemaVersion: 1,
    runId: 'synthetic-run',
    seed: 'synthetic-seed',
    configHash: hashA,
    inspectionHash: hashB,
    stratumRules: [
      { stratum: 'born-digital-en', rule: 'synthetic clean rule' },
      { stratum: 'layout-heavy-born-digital', rule: 'synthetic layout rule' },
      { stratum: 'scanned-degraded-en', rule: 'synthetic scan rule' },
      { stratum: 'scanned-degraded-thai-mixed', rule: 'synthetic Thai rule' },
    ],
    orderedCorpusCaseIds: ['F001', 'F002', 'F003', 'F004', 'F005', 'F006', 'F007', 'F008'],
    calibration: [
      { caseId: 'F001', stratum: 'born-digital-en', pageCount: 2 },
      { caseId: 'F002', stratum: 'layout-heavy-born-digital', pageCount: 2 },
      { caseId: 'F003', stratum: 'scanned-degraded-en', pageCount: 2 },
      { caseId: 'F004', stratum: 'scanned-degraded-thai-mixed', pageCount: 2 },
    ],
    evaluation: [
      { caseId: 'F005', stratum: 'born-digital-en', pageCount: 2, pages: [1, 2] },
      { caseId: 'F006', stratum: 'layout-heavy-born-digital', pageCount: 2, pages: [1, 2] },
      { caseId: 'F007', stratum: 'scanned-degraded-en', pageCount: 2, pages: [1, 2] },
      { caseId: 'F008', stratum: 'scanned-degraded-thai-mixed', pageCount: 2, pages: [1, 2] },
    ],
    manualReview: { status: 'complete', reviewedCaseIds: ['F001'], adjustments: [] },
    fallback: {
      applied: true,
      reasonCode: 'SYNTHETIC_FALLBACK',
      originalEvaluationPerStratum: 4,
      selectedEvaluationPerStratum: 1,
    },
    denominators: {
      corpusDocuments: 8,
      calibrationDocuments: 4,
      evaluationDocuments: 4,
      annotationPages: 8,
    },
  },
  artifact: {
    schemaVersion: 1,
    caseId: 'F001',
    cacheKey: hashB,
    tier: 'T0',
    provider: { id: 'synthetic', version: '1.0.0', execution: 'local' },
    parameters: {},
    representations: { text: 'synthetic text' },
    timings: { wallMs: 10, providerMs: null, providerTimingStatus: 'unavailable' },
    warnings: [],
  },
  'provider-probe': {
    schemaVersion: 1,
    tier: 'T0',
    id: 'synthetic-provider',
    execution: 'local',
    status: 'available',
    version: '1.0.0',
    checkedAt: '2026-08-05T00:00:00.000Z',
  },
  'provider-run': {
    schemaVersion: 1,
    caseId: 'F001',
    tier: 'T3',
    provider: {
      id: 'synthetic-vlm',
      version: 'unavailable',
      execution: 'local',
    },
    status: 'unavailable',
    cache: { hit: false },
    startedAt: '2026-08-05T00:00:00.000Z',
    finishedAt: '2026-08-05T00:00:00.001Z',
    error: { code: 'PROVIDER_UNAVAILABLE', message: 'Synthetic unavailable provider' },
  },
  decision: {
    schemaVersion: 1,
    caseId: 'F001',
    policyVersion: 'synthetic-v1',
    inspectionHash: hashA,
    initialTier: 'T0',
    rationale: ['TEXT_LAYER_INTACT'],
    confidence: 1,
    steps: [
      {
        tier: 'T0',
        artifactKey: hashB,
        passed: true,
        components: { characterSanity: 1 },
        reasons: [],
      },
    ],
    status: 'accepted',
    finalTier: 'T0',
    selectedArtifactKey: hashB,
  },
  annotation: {
    schemaVersion: 1,
    annotationStatus: 'complete',
    caseId: 'F001',
    page: 1,
    script: 'english',
    elements: [
      { id: 'e1', type: 'heading', text: 'Synthetic heading', readingOrder: 0 },
      { id: 'e2', type: 'body', text: 'Synthetic body', readingOrder: 1 },
    ],
    boundaryOpportunities: [
      {
        id: 'b1',
        type: 'heading-body',
        expectedAction: 'break',
        beforeElementId: 'e1',
        afterElementId: 'e2',
      },
    ],
    lowestUsableTier: 'T0',
    usableTiers: ['T0', 'T1', 'T2', 'T3'],
    lowestStructurallyAdequateTier: 'T1',
    structurallyAdequateTiers: ['T1', 'T2', 'T3'],
    structuralAssessmentConfirmed: true,
    higherTierDegraded: false,
    degradedTiers: [],
    acceptanceCriterionId: 'reading-sufficiency-v1',
    structuralCriterionId: 'structural-adequacy-v1',
    annotator: 'synthetic',
    judgedAt: '2026-08-05T00:00:00.000Z',
    structuralScope: {
      status: 'complete',
      ruleId: 'full-page-v1',
      description: 'Synthetic full-page structure.',
    },
    textReference: {
      status: 'unavailable',
      reason: 'Synthetic fixture does not require a text reference.',
    },
  },
  run: {
    schemaVersion: 1,
    runId: 'synthetic-run',
    experimentId: 'synthetic-experiment',
    seed: 'synthetic-seed',
    configHash: hashA,
    git: { commit: 'c'.repeat(40), dirty: true },
    runtime: { node: 'v20.9.0', pnpm: '11.10.0', java: null, tika: null, docling: null },
    system: {
      platform: 'synthetic',
      release: '1',
      architecture: 'arm64',
      cpuModel: 'synthetic',
      cpuCount: 1,
      totalMemoryBytes: 1024,
      accelerator: null,
    },
    providers: [],
    timingCalibrations: [
      {
        providerId: 'synthetic-docling',
        tiers: ['T1'],
        method: 'wall-minus-provider',
        calibrationControl: 'T1-born-digital',
        sampleCount: 1,
        fixedOverheadMs: 9,
        providerTimingStatus: 'observed',
        marginalTimeBasis: 'provider-reported',
        samples: [{ wallMs: 10, providerMs: 1 }],
        limitation: 'Synthetic timing calibration.',
      },
    ],
    tariffs: {
      currency: 'USD',
      cpuMachineHour: 0.1,
      gpuMachineHour: 1,
      basis: 'Synthetic declared proxy tariffs.',
    },
    limitations: ['Synthetic fixture'],
    startedAt: '2026-08-05T00:00:00.000Z',
  },
  'paper-value': {
    schemaVersion: 1,
    key: 'synthetic.metric',
    name: 'Synthetic metric',
    label: 'sampled',
    value: 0.5,
    unit: 'ratio',
    sourceRunId: 'synthetic-run',
    sourceMetric: 'synthetic.metric',
    numerator: 1,
    denominator: 2,
    excludedCount: 0,
    caseIds: ['F001'],
  },
} as const
